
server:
  port: 80
  servlet:
    context-path: /web

manager:
  username : tia
  password : tia

tia:
  port: 8080
  host: ${APP_HOST:0.0.0.0}
  #"alg":"HS256","typ":"JWT"
  token-key: ${APP_TOKEN_KEY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9}
  boss: 1
  worker: 16
  origin: http://localhost:8080

aliyun:
  oss:
    access-key-id: ${APP_OSS_KEY:1}
    access-key-secret: ${APP_OSS_SECRET:2}
    bucket: ${APP_OSS_BUCKET:kikyou}
    endpoint: ${APP_OSS_ENDPOINT:oss-cn-beijing.aliyuncs.com}

spring:
  data:
    redis:
      host: ${APP_REDIS_HOST:redis7}
      #password: ${APP_REDIS_PASS:redispw}
      port: ${APP_REDIS_PORT:6379}
      database: ${APP_REDIS_DATABASE:0}
      lettuce:
        pool:
          enabled: true
          # 连接池最大连接数（使用负值表示没有限制）
          maxactive: 64
          # 连接池中的最大空闲连接
          maxidle: 32
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          maxwait: 1000
          # 连接池中的最小空闲连接
          minidle: 8
  datasource:
    #通用配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://mysql8:3306/tia?serverTimezone=Asia/Shanghai&useUnicode=true&charcterEncoding=UTF-8&useSSL=false
    #数据源连接池配置
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 500000
      max-lifetime: 540000
      connection-timeout: 60000
      connection-test-query: select 1
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    mode: HTML
    encoding: utf-8
    servlet.content-type: text/html
    cache: false

  task:
    # Spring Task 调度任务的配置，对应 TaskSchedulingProperties 配置类
    scheduling:
      thread-name-prefix: tia-keepping- # 线程池的线程名的前缀。默认为 scheduling- ，建议根据自己应用来设置
      pool:
        size: 5 # 线程池大小。默认为 1 ，根据自己应用来设置
      shutdown:
        await-termination: true # 应用关闭时，是否等待定时任务执行完成。默认为 false ，建议设置为 true
        await-termination-period: 20000 # 等待任务完成的最大时长，单位为秒。默认为 0 ，根据自己应用来设置

cluster:
  model: standone #jgroups  standone
jgroups:
  clustername: ${JGROUPS_CLUSTER_NAME:tia-cluster}
  config: ${JGROUPS_CONFIG:jgroups-config-udp.xml}




monitor:
  appid: tia-monitor
  key: jvZJhHtp3vOVmpool6QlMw==




management:
  endpoints:
    enabled-by-default : false
    web:
      exposure:
        include: "*"
  #配置可远程使用    Actuator 关闭服务
  endpoint:
    shutdown:  #关闭服务
      enabled: false

